modLoader = "javafml"
loaderVersion = "[4,)" # Adjust to actual loader version range
license = "MIT"
logoFile = "logo.png"

[[mixins]]
config = "ancientnature.mixins.json"

[[mods]]
modId = "ancientnature"
version = "0.0.1"
displayName = "ยงlยง6Ancient ยง2Nature"
authors = "ANTeam"
description = "rawr mod horay"

[[dependencies."ancientnature"]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.146,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."ancientnature"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"