modLoader = "javafml"
loaderVersion = "[4,)" # Adjust to actual loader version range
license = "MIT"
logoFile = "logo.png"

[[mixins]]
config = "ancientnature.mixins.json"

[[mods]]
modId = "ancientnature"
version = "0.1.0"
displayName = "ยงlยง6Ancient ยง2Nature"
authors = "Reaper"
credits="Special thanks to Monkey_Biznec, small_chubby, Will, DinoFazbearYT, HappyG, Bretzelfresser, TheDarkPeasant, qBaumi, VoidArkana, ReinierTheGhost, Doot and Capt1444 for coding this. Thanks to the artists of ChipstheCat, Dororuw, AmyEpic, Raxiore, NM2, Koza, Aniriteron, GreenVaranus, Jurnaro, Gabe-esque, Tamalo20, GC, Evirapo, Grimzz and -Ghoul- for their help. Also special thx to the donors, specially my friends RomanSans and Yahrim for being at the beggining!"  #optional
description = "A nature from ancient times..."

[[dependencies."ancientnature"]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.146,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."ancientnature"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"